markdown: kramdown
permalink: pretty
highlighter: rouge

title: CUTE
logo-small: /img/logo-wide-white.png
logo: /img/logo-wide-dark.png

name: CUTE
description: C++ Unit Testing Easier
url: http://cute-test.com

collections:
  guides:
    output: true